spring.application.name=ai-voice-agent

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_voice_agent
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false